name: nkrs_app
description: "LankaCapital ERP App - Asset and Inventory Management System."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  google_fonts: ^8.0.2
  smooth_page_indicator: ^2.0.1
  iconsax_flutter: ^1.0.1
  timeline_tile: 2.0.0
  http: ^1.6.0 
  image_picker: ^1.0.4
  dio: ^5.9.2
  flutter_secure_storage: ^10.1.0
  jwt_decoder: ^2.0.1
  connectivity_plus: ^7.1.1
  internet_connection_checker: ^1.0.0+1
  sqflite_sqlcipher: ^3.4.0
  path: ^1.9.0
  local_auth: ^3.0.1
  phosphor_flutter: ^2.1.0
  intl: ^0.20.2

  # print_bluetooth_thermal: ^1.1.1     # classic Bluetooth thermal printer (Android)
  # esc_pos_utils_plus: ^2.0.4          # ESC/POS byte generation for the receipt
  # shared_preferences: ^2.2.3          # remembers the paired printer
  # http: ^1.2.1                        # calls your Spring Boot API
  # permission_handler: ^11.3.1         # runtime Bluetooth permissions

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo_2.png"
  android_13:
    image: "assets/logo_2.png"
    icon_background_color: "#ffffff"
    color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo_2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/logo.png